name: 'My First Github Actions'

on: push

jobs: 
  first_job: 
    name: 'First Job'
    runs-on: ubuntu-latest
    steps:
    - name: 'Say Hello World 1'
      shell: bash
      run: |
        echo: "Hello World from step #1"
    - name: 'Say Lorem Ipsum 2'
      shell: push
      run: |
        echo: "Lorem Ipsum from step #2"