name: 'My First GitHub Actions'

on: push

jobs:
  first_job:
    name: 'First Job'
    strategy:
      matrix: #job을 os에 맞춰서 세번 돌린다
        os : ['windows-latest', 'macos-latest', 'ubuntu-latest']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Say Hello World from ${{ matrix.os }}
        shell: bash
        run: |
          echo "Hello, from ${{ matrix.os }}"